{% set name = "langcodes" %}
{% set version = "3.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1eef8168d07e51e131a2497ffecad4b663f6208e7c3ae3b8dc15c51734a6f801

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - pip
    - setuptools >=60
    - setuptools-scm >=8.0
    - wheel
    - python
  run:
    - python
    - language-data >=1.2

test:
  source_files:
    - langcodes/tests
  imports:
    - langcodes
    - langcodes.data_dicts
    - langcodes.language_distance
    - langcodes.language_lists
    - langcodes.registry_parser
    - langcodes.tag_parser
    - langcodes.util
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -ra -vv langcodes/tests

about:
  home: https://github.com/georgkrause/langcodes
  summary: Tools for labeling human languages with IETF language tags
  license: MIT
  license_file: LICENSE.txt
  license_family: MIT
  description: |
    Langcodes is a toolkit for working with and comparing the
     standardized codes for languages, such as 'en' for English, 'es'
     for Spanish, and 'zh-Hant' for Traditional Chinese. These are
     BCP 47 language codes, formerly known as ISO language codes.
  dev_url: https://github.com/georgkrause/langcodes
  doc_url: https://github.com/georgkrause/langcodes/tree/main/docs

extra:
  recipe-maintainers:
    - thewchan
